server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /auth/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
    }

    location /files {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        client_max_body_size 25m;
    }

    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_read_timeout 120;
        client_max_body_size 25m;
    }

    location /chat/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, must-revalidate";
    }
}
